### ISSUE TITLE
Some small questions。

### ISSUE THREAD

**Issue by lnq325805524** [XiaoxFeng/RINet#2]
First, thanks for your nice work. 
Just some questions below:
1. In my experiments, I found the results from NWPUv2 very unstable in WSOD. The results can even fluctuate within 20 percent. For example, PCL can achieve similarly 40% to 60% accuracy in my experimental setting. Do you select the highest results as the results?
2. Which combination within backbone and rpn do you use? C4 or FPN.
Looking forward to your reply and code release!

**Comment by XiaoxFeng** [comment]
In our experiments, the detection results is stable. It depends on your baseline framework. Note that different frameworks load proposals in different orders ( i.e., MELM(x1,x2,y1,y2) but PCL(x1,y1,x2,y2)). You can obtain stable results on the PCL which is implemented with caffe. Besides, we did not introduce RPN and FPN in our work, the feature of Conv5_3 on VGG16 is selected. The code will be released in July.

**Comment by lnq325805524** [comment]
您的邮件已收到，谢谢

**Comment by lnq325805524** [comment]
Thanks for your reply, I will make a further examination.

**Comment by Tarazed** [comment]
> Thanks for your reply, I will make a further examination.

Hi, have you examined it? I find the annotations of NWPU VHR-10.v2 are not correct, many boxes are wrongly annotated, and that may be the reason.
