### ISSUE TITLE
Could you please release the selective search data of NWPUv2?

### ISSUE THREAD

**Issue by lnq325805524** [XiaoxFeng/RINet#9]
I can only find the selective search data of NWPU.

**Comment by XiaoxFeng** [comment]
The released selective search data (NWPU) is NWPU.V2.

2023-02-24 08:23:56 "lnq325805524" ***@***.***> 写道：

I can only find the selective search data of NWPU.

**Comment by lnq325805524** [comment]
Oh, I see. You just put the selective search data of train to the training process, not selective search data of trainval. Is that correct?

**Comment by XiaoxFeng** [comment]
Yes, it is.发自我的手机-------- 原始邮件 --------发件人： lnq325805524 ***@***.***>日期： 2023年2月25日周六 中午12:00收件人： XiaoxFeng/RINet ***@***.***>抄送： XiaoxFeng ***@***.***>, Comment ***@***.***>主    题： Re: [XiaoxFeng/RINet] Could you please release the selective search data of NWPUv2? (Issue #9)
Oh, I see. You just put the selective search data of train to the training process, not selective search data of trainval. Is that correct?

**Comment by lnq325805524** [comment]
Thanks

**Comment by z211131721** [comment]
> Thanks

Hi, have you tried to run the evaluated code of measuring CorLoc (NWPUv2) ? 
In my experimental environment, the CorLoc of NWPUv2 seems wrong.

**Comment by lnq325805524** [comment]
> 

Sorry, I didn't run the code.

**Comment by lnq325805524** [comment]
> > Thanks
> 
> Hi, have you tried to run the evaluated code of measuring CorLoc (NWPUv2) ? In my experimental environment, the CorLoc of NWPUv2 seems wrong.

Sorry, I didn't run the code
